config/routes.rb
Rails.application.routes.draw do
  # get 'messages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages
  root 'messages#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:edit, :update, :show, :destroy]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(post_params)
    if @message.save 
      redirect_to @message
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @message.update(post_params)
      redirect_to @message
    else
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to messages_path
  end

  private

  def find_message
    @message = Message.find(params[:id])
  end

  def post_params
    params.require(:message).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmpTrackTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home', root_path %>
    <%= link_to 'All Messages', messages_path %>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
    <%= f.label :Message %><br>
    <%= f.text_area :body %><br>
    <br>
    <%= f.submit %>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
    <h2>Message no. <%= message.id %> is:</h2>
    <div> 
        <%= truncate(message.body, :length => 20) %>
    </div>
    <br>
    <%= link_to 'Read Message', message %>
<% end %>

app/views/messages/new.html.erb
<h1>Create a new message</h1>

<%= render 'form' %>

app/views/messages/show.html.erb
<h1>The message is:</h1>
<br>

<div>
    <%= @message.body %>
</div>
<br>
<%= link_to 'Edit Message', edit_message_path(@message) %>

<%= link_to 'Delete Message', message_path(@message), method: :delete, data: {confirm: "Are you sure you want to delete this message?"} %>